def words():
    
    plural_noun = input("Enter a plural noun: ")
    adjective = input("Enter an adjective: ")
    plural_noun_animals = input("Enter a plural noun; animals ")
    plural_noun2 = input("Enter a plural noun: ")
    adjective2 = input("Enter an adjective: ")
    color = input("Enter a color: ")
    adjective3 = input("Enter an adjective: ")
    noun = input("enter a noun: ")
    plural_noun3 = input("Enter a plural noun: ")
    adjective4 = input("Enter an adjective: ")
    verb = input("Enter a verb: ")
    plural_noun4 = input("Enter a plural noun: ")
    verbed = input("Enter a verb ending in \"ed\": ")
    verb2 = input("Enter a verb: ")
    noun2 = input("enter a noun: ")
    adjective5 = input("Enter an adjective: ")


    print("Unicorns aren't like other " + plural_noun + ";")
    print("they're " + adjective + ". They look like")
    print(plural_noun_animals + " with " + plural_noun2 + " for feet")
    print("and a " + adjective2 + " mane of hair. But unicorns")
    print("are " + color + " and have a " + adjective3 + " " + noun+ " on")
    print("their heads. Some " + plural_noun3 + " don't")
    print("believe unicorns are " + adjective4 + " but I do")
    print("I would love to " + verb + " a")
    print("unicorn to faraway " + plural_noun4 + " . One thing")
    print("I've always " + verbed + " about is whether")
    print("unicorns " + verb2 + " rainbows, or is their")
    print(noun2 + " " + adjective5 + " like any other animal's?")

words()
